### ISSUE TITLE
Love This Program, But...

### ISSUE THREAD

**Issue by JMHBM** [alexkdeveloper/forgetpass#2]
Are there any plans on releasing this for Android as well? 

I'm using LMDE5 on my laptop and absolutely love it.

Thanks 👍🙏👍

**Comment by alexkdeveloper** [comment]
Hi!
I am very glad that you liked my app)
I don't create Android apps, but...
there is a website like this:
https://obliviate.app/
The site does the same thing as my app, and works great on mobile devices.
