### ISSUE TITLE
Hard to distinguish logo's handle 

### ISSUE THREAD

**Issue by ghost** [alexkdeveloper/forgetpass#6]
Hi,

Thanks for application. It's a bit hard to see logo's hande.

OS: Ubuntu 22.04.1
Theme: Default

![Ekran Görüntüsü - 2022-09-30 22-20-21](https://user-images.githubusercontent.com/6218679/193342161-2ab3073e-f361-4a77-b9b2-80679340dc89.png)

**Comment by ghost** [comment]
I changed handle's color to green to test it. It seemed to me a bit better.

![Ekran Görüntüsü - 2022-09-30 23-04-49](https://user-images.githubusercontent.com/6218679/193348222-80df01d4-78fc-420e-ba46-7cab81dac5fb.png)


![com github alexkdeveloper forgetpass](https://user-images.githubusercontent.com/6218679/193347410-3b8bf5d1-0e59-4817-bbac-edf2c61b7e38.svg)

**Comment by alexkdeveloper** [comment]
Looks good!
