### ISSUE TITLE
Include the new icon on README.md

### ISSUE THREAD

**Issue by IngrownMink4** [alexkdeveloper/forgetpass#8]
It would be nice if you put the new icon in README.md (right now it's quite empty…)

![Captura desde 2022-10-03 16-55-26](https://user-images.githubusercontent.com/25466522/193608931-ca0efb79-3c7a-4189-880f-a20047def444.png)

**Comment by alexkdeveloper** [comment]
The above image uses the old icon. It is advisable to translate the inscription into English.
