### ISSUE TITLE
Not Really an Issue, But Kinda Is?

### ISSUE THREAD

**Issue by JMHBM** [alexkdeveloper/forgetpass#9]
Hello,

I've been using various distros for quite a few years now and recently stumbled upon ForgetPass. It's truly a wonderful, yet simple, application that I've been using to password protect my files before uploading them to the cloud. But, a few days ago, I decided to switch to Windows 11 Pro (don't worry, it's been modified to keep Microsoft out of my business). I've searched online as well as Git and haven't been able to find ForgetPass for Windows yet. 

If it isn't too much to ask (since I don't know how to build apps from source yet), is it possible to create either a portable .exe file or installer for Windows so I can continue using your incredible little app? Thanks in advance for your help and please, stay safe.

**Comment by alexkdeveloper** [comment]
Hi!
I develop programs only under Linux.
You can use the link below to the website to generate passwords.
https://obliviate.app/
